>
# Daily Briefing #}
{%- macro getGreeting() -%}
    {% if now().strftime('%H')|int < 12 %}
      Good morning.
    {% elif now().strftime('%H')|int >= 12 and now().strftime('%H')|int < 18 %}
      Good afternoon.
    {% else %}
      Good evening.
    {% endif %}

  {% if is_state('binary_sensor.morning','on') %}
    Today is {{states.sensor.today_is.state }}, {{ as_timestamp(now()) | timestamp_custom('%B %d, %H:%M') }}.
  {% else %}
    It is {{ now().strftime("%H:%M") }}.
  {% endif %}

{%- endmacro -%}

{%- macro getRepportStatus() -%}

<p> # Doors and windos #
  {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_f52d9007_on_off', 'on') %}
  Studio Porch is open.
  {% endif %}
  {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_d41dd107_on_off', 'on') %}
  Bedroom Window is open.
      {% if state_attr('weather.smhi_home_stockholm','temperature')|float >= 16 %}
       It is warm outside, so it can bee open.
      {% else %}
      Do not let all heat get away.
      {% endif %}
  {% endif %}
  {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_f8ab8906_on_off', 'on') %}
  Kitchen Window is open.
  {% endif %}
  {% if is_state('binary_sensor.lumi_lumi_sensor_magnet_aq2_on_off', 'on') %}
  The front Door is open.
  {% endif %}
  {% if is_state('group.magnet_sensors_all', 'off') %}
  Doors and windows are Closed.
  {% endif %}
</p>

<p> # Doors trigger #
  The door motion have been triggerd {{ states.counter.door_motion_counter.state }} times, the last 24 houers.
  {{ states.counter.door_motion_counter_night.state }} off the triggers where during night time.
</p>

<p> # Washer #
  {% if is_state('input_boolean.washer_completed', 'on') %}
  Youre Washing are done . Emty the washer before it stinks up the apartment.
  {% endif %}
</p>

<p>
End off rapport
</p>

{%- endmacro -%}








{# a macro that removes all newline characters, empty spaces, and returns formatted text #}
{%- macro cleanup(data) -%}
  {%- for item in data.split("\n")  if item | trim != "" -%}
    {{ item | trim }} {% endfor -%}
{%- endmacro -%}

{# a macro to call all macros :)  #}
{%- macro mother_of_all_macros() -%}
  {{ getGreeting() }}
  {{ getRepportStatus()}}

{%- endmacro -%}

  {# Call the macro  #}
{{- cleanup(mother_of_all_macros()) -}}
