homeassistant:
    packages: !include_dir_named packages

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

########### Alarm Penel ###############################
alarm_control_panel:
  - platform: manual
    code: !secret alarm_password
    delay_time: 30
    arming_time: 30
    trigger_time: 30
############ Wake On Lan #####################################
switch:
  - platform: wake_on_lan
    mac: !secret computer_mac
    name: “COMPUTER STUDIO”
    host: !secret computer_host
###### THIS CONFIG INCLUDE THIS FILES #########
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
light: !include lights.yaml
sensor: !include sensors.yaml
############# Alexa Notification #################################
input_text:
  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'
#### Time of Day ########################################
binary_sensor:
  - platform: tod
    name: Morning
    after: "05:00"
    before: "12:00"
  - platform: tod
    name: Day
    after: "12:00"
    before: "18:00"
  - platform: tod
    name: Evening
    after: "18:00"
    before: "23:00"
  - platform: tod
    name: Night
    after: "23:00"
    before: "05:00"
############### Camera ######################################
