## Sensor for Home Assistant ############################
- platform: systemmonitor
  resources:
  - type: processor_use
  - type: disk_use_percent
    arg: "/"
  - type: disk_free
    arg: "/"
  - type: memory_use_percent
  - type: network_in
    arg: eth0
  - type: throughput_network_in
    arg: eth0
  - type: network_out
    arg: eth0
  - type: throughput_network_out
    arg: eth0
  - type: processor_temperature
  - type: last_boot
# Sensor for last echo call
- platform: template
  sensors:
    last_alexa:
      entity_id:
        - media_player.echo_show
        - media_player.bedroom_echo_dot
        - media_player.studio_echo_dot
      value_template: >
        {{ states.media_player | selectattr('attributes.last_called','eq',True) | map(attribute='entity_id') | first }}
  # '{{ states(''sensor.last_alexa'') }}' ## <---Template Adress for this sensor##
#############-Washer Sensor ##########################################
- platform: template
  sensors:
    washer_maskin:
      value_template: >
        {% if states("sensor.washer_power")|float == 0  %}
          Off
        {% elif states("sensor.washer_power")|float <= 1.3 %}
          Standby
        {% else %}
          Washing
        {% endif %}
      icon_template: >-
        {% if states("sensor.washer_power")|float == 0  %}
        mdi:washing-machine-off
        {% elif states("sensor.washer_power")|float <= 1  %}
        mdi:washing-machine-alert
        {% else %}
        mdi:washing-machine
        {% endif %}
################### Low Battery Sensor ####################################
- platform: template
  sensors:
    low_battery:
      friendly_name: Low Battery
      value_template: >
        {% set output = namespace(sensors=[]) %}
        {% for state in states.sensor | selectattr('attributes.device_class', '==', 'battery') %}
          {% if 0 <= state.state | int(-1) < 20 | int  %}
             {% set output.sensors = output.sensors + [state.name ~ ' (' ~ state.state ~ ' %)'] %}
          {% endif %}
        {% endfor %}
############# Time Of Day Sensor ################################
- platform: template
  sensors:
    time_off_day:
      friendly_name: "Time Off Day"
      value_template: >-
        {% if is_state('binary_sensor.morning','on') %}
          Morning
        {% elif is_state('binary_sensor.day','on') %}
          Day
        {% elif is_state('binary_sensor.evening','on') %}
          Evening
        {% else %}
          Night
        {% endif %}
      icon_template: >-
        {% if is_state('binary_sensor.morning','on') %}
        mdi:weather-sunset-up
        {% elif is_state('binary_sensor.day','on') %}
        mdi:white-balance-sunny
        {% elif is_state('binary_sensor.evening','on') %}
        mdi:weather-sunset-down
        {% else %}
        mdi:weather-night
        {% endif %}
############### Door Motion Sensor ##########################################
